// <auto-generated />
using System;
using LuloApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuloApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728151653_AgregarTemporadaYFechaCreacion")]
    partial class AgregarTemporadaYFechaCreacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuloApp.Api.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Codigo = "VES-01",
                            Descripcion = "Saco blanco de niña.",
                            FechaCreacion = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "/imagenes/saco_blanco.avif",
                            Nombre = "Saco Lulo Spring",
                            Precio = 85000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            FechaCreacion = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "/imagenes/saco_azul_oscuro.webp",
                            Nombre = "Saco Azul Oscuro",
                            Precio = 120000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            FechaCreacion = new DateTime(2026, 7, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "/imagenes/saco_azul_claro.avif",
                            Nombre = "Saco Azul Claro",
                            Precio = 120000m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            FechaCreacion = new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenUrl = "/imagenes/camisa_pastel.avif",
                            Nombre = "Camisa Nube",
                            Precio = 120000m
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoMateriales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "Lino"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "Lana"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "Lana"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "Lino"
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId", "Talla", "Color")
                        .IsUnique();

                    b.ToTable("ProductoStock", (string)null);
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoTemporada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoTemporadas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "Primavera"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "Invierno"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "Otoño"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "Verano"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000005"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "Verano"
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoMaterial", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Materiales")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoStock", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Stock")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoTemporada", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Temporadas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.Producto", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Stock");

                    b.Navigation("Temporadas");
                });
#pragma warning restore 612, 618
        }
    }
}
