// <auto-generated />
using System;
using LuloApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuloApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728043553_ReorganizarTallasColoresMateriales")]
    partial class ReorganizarTallasColoresMateriales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuloApp.Api.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = "VES-01",
                            Descripcion = "Saco blanco de niña.",
                            ImagenUrl = "/imagenes/saco_blanco.avif",
                            Nombre = "Saco Lulo Spring",
                            Precio = 85000m
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/saco_azul_oscuro.webp",
                            Nombre = "Saco Azul Oscuro",
                            Precio = 120000m
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/saco_azul_claro.avif",
                            Nombre = "Saco Azul Claro",
                            Precio = 120000m
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/camisa_pastel.avif",
                            Nombre = "Camisa Nube",
                            Precio = 120000m
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoColores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "Blanco"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "Crema"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "Azul Oscuro"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "Azul Claro"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "Pastel"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "Multicolor"
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoMateriales", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "Lino"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "Lana"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "Lana"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "Lino"
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoTalla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("ProductoTallas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "S"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "M"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "L"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            ProductoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Valor = "XL"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "S"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "M"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "L"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            ProductoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Valor = "XL"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "S"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "M"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "L"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            ProductoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Valor = "XL"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000013"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "S"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000014"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "M"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000015"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "L"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000016"),
                            ProductoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Valor = "XL"
                        });
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoColor", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Colores")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoMaterial", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Materiales")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.ProductoTalla", b =>
                {
                    b.HasOne("LuloApp.Api.Models.Producto", null)
                        .WithMany("Tallas")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LuloApp.Api.Models.Producto", b =>
                {
                    b.Navigation("Colores");

                    b.Navigation("Materiales");

                    b.Navigation("Tallas");
                });
#pragma warning restore 612, 618
        }
    }
}
