// <auto-generated />
using System;
using LuloApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LuloApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260728040620_InicialProductos")]
    partial class InicialProductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LuloApp.Api.Models.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Tallas")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Codigo = "VES-01",
                            Descripcion = "Saco blanco de niña.",
                            ImagenUrl = "/imagenes/saco_blanco.avif",
                            Material = "Lino",
                            Nombre = "Saco Lulo Spring",
                            Precio = 85000m,
                            Tallas = "S,M,L,XL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/saco_azul_oscuro.webp",
                            Material = "Lana",
                            Nombre = "Saco Azul Oscuro",
                            Precio = 120000m,
                            Tallas = "S,M,L,XL"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/saco_azul_claro.avif",
                            Material = "Lana",
                            Nombre = "Saco Azul Claro",
                            Precio = 120000m,
                            Tallas = "S,M,L,XL"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Codigo = "CHA-02",
                            Descripcion = "Chaqueta de jean clásica que combina con todo.",
                            ImagenUrl = "/imagenes/camisa_pastel.avif",
                            Material = "Lino",
                            Nombre = "Camisa Nube",
                            Precio = 120000m,
                            Tallas = "S,M,L,XL"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
